### ISSUE TITLE
Chapter 2 Exercise Solutions & Discussion

### ISSUE THREAD

**Issue by jjhampton** [OperationCode/eloquent-js#2]
For Chapter 2, I'll post my solutions to the exercises in here.  If anyone else wants to join in, you can post a link to your solutions in here on this issue too (as a GitHub Gist / CodePen / GitHub repo link / anything else).  This way, if anyone has questions or wants to comment on anyone else's solutions, we should be able to post directly in the issue thread here to get some discussion going.

I'm open to any other ways to constructively post solutions and allow for discussion/collaboration.

**Comment by jjhampton** [comment]
My Chapter 2 Exercise Solutions: https://gist.github.com/jjhampton/54bb51677ff58ad0324cd5cb2e531f92

I tried to throw in a couple comments for anything that might require extra explanation.  I had to include `'use strict'` at the top of my file to allow for ES6 `let` statements to work when running my solution file locally in Node.js.

**Comment by ghost** [comment]
Here are my solutions: https://gist.github.com/yeli-buonya/1ee2da52b4779d1ca9e552a94bd8806e

Any feedback is welcome.

**Comment by jjhampton** [comment]
@yeli-buonya Awesome, left you some feeback on the Gist.

**Comment by jjhampton** [comment]
@CodeNeophyte Your ChessBoard exercise works similarly to @ yeli-buonya's above - the width isn't changing along with the height when you change the `size` variable.   Left a comment on his Gist above that may relate to your answer as well ^

**Comment by jjhampton** [comment]
Closing - discussion for Chapter exercises has been taking place in PRs.
